// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU5Y1PHtH2KBCg3MII_KgvbOhBD9QV5C4',
    appId: '1:126913678992:android:39b1a0f021e9655dcbd215',
    messagingSenderId: '126913678992',
    projectId: 'movie-app-recommendation',
    databaseURL: 'https://movie-app-recommendation-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'movie-app-recommendation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyg4ybgbDQWyi4eLvHwMG_Gx1IYsN5nxs',
    appId: '1:126913678992:ios:c2c658c8dfa374cccbd215',
    messagingSenderId: '126913678992',
    projectId: 'movie-app-recommendation',
    databaseURL: 'https://movie-app-recommendation-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'movie-app-recommendation.appspot.com',
    iosBundleId: 'com.example.movieRecommendationAppCourse',
  );
}
